<?php
return array(
  "user/login" =>"user/login",
  "user/registration" =>"user/registration",
  "user/logout" => "user/logout",
  "profile/order/delete/([0-9]+)" => "user/deleteProfileOrder/$1",
  "admin/addDelivery/delete/([0-9]+)" => "adminOrder/deleteDelivery/$1",
  "admin/listOrders/delete/([0-9]+)" => "adminOrder/deleteOrder/$1",
  "admin/supplier/delete/([0-9]+)" => "adminSupplier/deleteSupplier/$1",
  "admin/product/delete/([0-9]+)" => "adminProduct/deleteProduct/$1",
  "admin/category/delete/([0-9]+)" => "adminCategory/deleteCategory/$1",
  "admin/stock/delete/([0-9]+)" => "adminStock/deleteStock/$1",
  "admin/importData/delete/([0-9]+)" => "adminStock/deleteImportData/$1",
  "admin/orderItem/([0-9]+)" => "adminOrder/orderItem/$1",
  "admin/orderItem/delete/([0-9]+)" => "adminOrder/deleteOrderItem/$1",
  "admin/listOrders/delete/([0-9]+)" => "adminOrder/deleteListOrders/$1",
  "admin/addProduct" => "adminProduct/addProduct",
  "admin/addProduct" => "adminProduct/addProduct",
  "admin/addSupplier" => "adminSupplier/addSupplier",
  "admin/listProduct" => "adminProduct/listProduct",
  "admin/addOnStock" => "adminStock/addOnStock",
  "admin/listStock" => "adminStock/listStock",
  "admin/listOrders" => "adminOrder/listOrders",
  "admin/addDelivery" => "adminOrder/addDelivery",
  "admin/category" => "adminCategory/category",
  "admin" => "admin/index",

  "search" => "site/search",
  "profile" => "user/profile",
  "cart/AddOrder" => "site/addOrder",
  "cart/delete/([0-9]+)" => "site/deleteCart/$1",
  "cart" => "site/cart",
  "product/([0-9]+)" => "site/productData/$1",
  "category/([0-9]{1,4})" => "site/category/$1",
  "category" => "site/category",
  "" => "site/index",
  "index.php"=> "site/index"
);
?>
